additional tools
cevi/Cevi-Tools-Webpage pull request #65
Opened 2024-10-20 14:39 UTC by patrickuhlmann

add cevimail and ceviwiki

2024-10-20 14:48 UTC, maede97 requested changes
two remarks for the clipboard images.

2024-10-20 14:48 UTC, maede97 commented on assets/tools-frontpage/Source/kursfinder.png
can we only store a link to this and not the screenshot of the page?

2024-10-20 14:48 UTC, maede97 commented on assets/tools-frontpage/Source/ceviemail.png
can we only store a link to this and not the screenshot of the page?

2024-10-20 15:13 UTC, patrickuhlmann commented on assets/tools-frontpage/Source/kursfinder.png
ok fine

2024-10-20 15:13 UTC, patrickuhlmann commented on assets/tools-frontpage/Source/ceviemail.png
ok fine

2024-10-21 08:29 UTC, wp99cp approved these changes
looks fine to me now

2024-10-21 09:01 UTC, maede97 commented
Why do we need to store the pictures now twice? once in source folder, once outside?
isn't it enough to store them where the image is actually needed and in the source folder we only store the txt file?

2024-10-21 09:05 UTC, patrickuhlmann commented
I edited the images 

> Why do we need to store the pictures now twice? once in source folder, once outside? isn't it enough to store them where the image is actually needed and in the source folder we only store the txt file?

I edited the images that we actually use (made them quadratic), the original images can be used for reverse image search or also if other editing (e. g. adding cevi logo etc.) should take place. Images can disappear from openclipart. The idea of the original webpage screenshot was also to have some proof that the images are actually from openclipart and see the name of the author etc.Just to have something to work in case there would be an Abmahnung or something similar.

2024-10-29 22:27 UTC, patrickuhlmann commented
> two remarks for the clipboard images.

Can I merge it?

2024-10-30 05:00 UTC, maede97 commented
Sorry, did not see your comment before. Merge it! :-)

2024-10-30 05:00 UTC, maede97 approved these changes

2024-10-31 20:48 UTC, merged